[completion.active]
bg = "#5a524c"
fg = "#d3869b"

[completion.border]
fg = "#7daea3"

[completion.inactive]
fg = "#ddc7a1"

[[filetype.rules]]
fg = "#89b482"
mime = "image/*"

[[filetype.rules]]
fg = "#d8a657"
mime = "video/*"

[[filetype.rules]]
fg = "#d8a657"
mime = "audio/*"

[[filetype.rules]]
fg = "#d3869b"
mime = "application/zip"

[[filetype.rules]]
fg = "#d3869b"
mime = "application/gzip"

[[filetype.rules]]
fg = "#d3869b"
mime = "application/tar"

[[filetype.rules]]
fg = "#d3869b"
mime = "application/bzip"

[[filetype.rules]]
fg = "#d3869b"
mime = "application/bzip2"

[[filetype.rules]]
fg = "#d3869b"
mime = "application/7z-compressed"

[[filetype.rules]]
fg = "#d3869b"
mime = "application/rar"

[[filetype.rules]]
fg = "#d3869b"
mime = "application/xz"

[[filetype.rules]]
fg = "#a9b665"
mime = "application/doc"

[[filetype.rules]]
fg = "#a9b665"
mime = "application/pdf"

[[filetype.rules]]
fg = "#a9b665"
mime = "application/rtf"

[[filetype.rules]]
fg = "#a9b665"
mime = "application/vnd.*"

[[filetype.rules]]
bold = true
fg = "#7daea3"
mime = "inode/directory"

[[filetype.rules]]
fg = "#ddc7a1"
mime = "*"

[help.desc]
fg = "#ddc7a1"

[help.footer]
fg = "#ddc7a1"

[help.hovered]
bg = "#5a524c"
fg = "#ddc7a1"

[help.on]
fg = "#d3869b"

[help.run]
fg = "#89b482"

[input.border]
fg = "#7daea3"

[input.selected]
bg = "#5a524c"

[input.title]
fg = "#ddc7a1"

[input.value]
fg = "#ddc7a1"

[mgr]
# syntect_theme = "/nix/store/gh9bngvn85y4wjixvf3cl5g21qxbnsch-base16-gruvbox-material-dark-hard.tmTheme"

[mgr.border_style]
fg = "#bdae93"

[mgr.count_copied]
bg = "#a9b665"
fg = "#202020"

[mgr.count_cut]
bg = "#ea6962"
fg = "#202020"

[mgr.count_selected]
bg = "#d8a657"
fg = "#202020"

[mgr.cwd]
fg = "#89b482"

[mgr.find_keyword]
bold = true
fg = "#a9b665"

[mgr.find_position]
fg = "#d3869b"

[mgr.hovered]
bg = "#504945"
bold = true

[mgr.marker_copied]
bg = "#a9b665"
fg = "#a9b665"

[mgr.marker_cut]
bg = "#ea6962"
fg = "#ea6962"

[mgr.marker_selected]
bg = "#d8a657"
fg = "#d8a657"

[mgr.preview_hovered]
bg = "#504945"
bold = true

[mode.normal_alt]
bg = "#202020"
fg = "#7daea3"

[mode.normal_main]
bg = "#7daea3"
bold = true
fg = "#202020"

[mode.select_alt]
bg = "#202020"
fg = "#a9b665"

[mode.select_main]
bg = "#a9b665"
bold = true
fg = "#202020"

[mode.unset_alt]
bg = "#202020"
fg = "#bd6f3e"

[mode.unset_main]
bg = "#bd6f3e"
bold = true
fg = "#202020"

[pick.active]
fg = "#d3869b"

[pick.border]
fg = "#7daea3"

[pick.inactive]
fg = "#ddc7a1"

[status.perm_exec]
fg = "#a9b665"

[status.perm_read]
fg = "#d8a657"

[status.perm_sep]
fg = "#89b482"

[status.perm_type]
fg = "#7daea3"

[status.perm_write]
fg = "#ea6962"

[status.progress_error]
bg = "#202020"
fg = "#ea6962"

[status.progress_label]
bg = "#202020"
fg = "#ddc7a1"

[status.progress_normal]
bg = "#202020"
fg = "#ddc7a1"

[tabs.active]
bg = "#7daea3"
bold = true
fg = "#202020"

[tabs.inactive]
bg = "#2a2827"
fg = "#7daea3"

[tasks.border]
fg = "#7daea3"

[tasks.hovered]
bg = "#5a524c"
fg = "#ddc7a1"

[tasks.title]
fg = "#ddc7a1"

[which.cand]
fg = "#89b482"

[which.desc]
fg = "#ddc7a1"

[which.mask]
bg = "#504945"

[which.rest]
fg = "#bd6f3e"

[which.separator_style]
fg = "#bdae93"
